#!/bin/sh
### BEGIN INIT INFO
# Provides:          FTS-deamon
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start script for FTSKonsole
# Description:       Enable service provided by FTS-deamon
### END INIT INFO


FTS_CFG="video"

# kFreeBSD do not accept scripts as interpreters, using #!/bin/sh and sourcing.
if [ true != "$INIT_D_SCRIPT_SOURCED" ] ; then
    set "$0" "$@"; INIT_D_SCRIPT_SOURCED=true . /lib/init/init-d-script
fi


#DESC="FTS-video"
#DEAMON=watchdogFTS.sh

FTS_PATH="SET FTS_PATH"

case "$1" in
        start)
                cd ${FTS_PATH}
                ./watchdogFTS.sh ${FTS_CFG}  ${FTS_PATH} &
                echo "$(date) sercice FTS-deamon started" >> /var/log/FTSdeamon
        ;;
        stop)
                sudo killall watchdogFTS.sh
                killall FTSKonsole
                echo "$(date) service FTS-deamon stopped" >> /var/log/FTSdeamon
        ;;
        restart)
                $0 stop
                $0 start
        ;;
        status)
        ;;
        *)
                echo "Usage $0 {start|stop|restart|status}"
        ;;
esac

exit 0
